### ISSUE TITLE
-? and -h do nothing

### ISSUE THREAD

**Issue by Kamek437** [horsing/coder#1]
coder.exe -? doesn't print anything. Also, there is no output when I run it at all how do I know it worked? More docs are needed here is this abandoned? I have made a .workspace file in my home and run coder.exe. It outputs nothing and there is no ws.exe or other. I would be willing to work on documentation and such for this if it's needed, I'm trying to get more experience with git.

**Comment by cloorc** [comment]
Sorry, let me check it
